// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnIB1yrbPZq5IWlzDn2Uq_dAbvHrDS-8E',
    appId: '1:978743276444:web:59abfceae066174c4a8e59',
    messagingSenderId: '978743276444',
    projectId: 'meal-planing-app',
    authDomain: 'meal-planing-app.firebaseapp.com',
    storageBucket: 'meal-planing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuAV0udDaKI0mrSitXAUxJUPL9Sa9DJE',
    appId: '1:978743276444:android:e8fd642f95e25e454a8e59',
    messagingSenderId: '978743276444',
    projectId: 'meal-planing-app',
    storageBucket: 'meal-planing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7WviAgHWeTcDzwuFD_4pn3c5AsE9_Ys',
    appId: '1:978743276444:ios:6a773054cb4975c84a8e59',
    messagingSenderId: '978743276444',
    projectId: 'meal-planing-app',
    storageBucket: 'meal-planing-app.firebasestorage.app',
    iosBundleId: 'com.example.mealPlaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7WviAgHWeTcDzwuFD_4pn3c5AsE9_Ys',
    appId: '1:978743276444:ios:6a773054cb4975c84a8e59',
    messagingSenderId: '978743276444',
    projectId: 'meal-planing-app',
    storageBucket: 'meal-planing-app.firebasestorage.app',
    iosBundleId: 'com.example.mealPlaning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnIB1yrbPZq5IWlzDn2Uq_dAbvHrDS-8E',
    appId: '1:978743276444:web:80784470dd33d22a4a8e59',
    messagingSenderId: '978743276444',
    projectId: 'meal-planing-app',
    authDomain: 'meal-planing-app.firebaseapp.com',
    storageBucket: 'meal-planing-app.firebasestorage.app',
  );
}
